// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EXAM_SYSTEM_API.Domain.Entities;

public partial class EsChoice
{
    /// <summary>
    /// รหัสตัวเลือก
    /// </summary>
    public int ChoiceId { get; set; }

    /// <summary>
    /// รหัสคำถามที่ตัวเลือกนี้เป็นของมัน
    /// </summary>
    public int QuestionId { get; set; }

    /// <summary>
    /// เนื้อหาของตัวเลือก
    /// </summary>
    public string ChoiceText { get; set; }

    /// <summary>
    /// ระบุว่าตัวเลือกนี้เป็นคำตอบที่ถูกต้องหรือไม่ (true/false)
    /// </summary>
    public bool IsCorrect { get; set; }
}