// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EXAM_SYSTEM_API.Domain.Entities;

public partial class EsExamTaken
{
    /// <summary>
    /// รหัสของการสอบ
    /// </summary>
    public int ExamTakenId { get; set; }

    /// <summary>
    /// รหัสของ Part ที่กำลังสอบ
    /// </summary>
    public int ScheduleId { get; set; }

    /// <summary>
    /// เวลาที่เริ่มสอบ
    /// </summary>
    public TimeOnly StartedTime { get; set; }

    /// <summary>
    /// เวลาที่ส่งข้อสอบ
    /// </summary>
    public TimeOnly? SubmittedTime { get; set; }

    public double? Score { get; set; }

    /// <summary>
    /// สถานะการสอบ
    /// </summary>
    public string Status { get; set; }
}