// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EXAM_SYSTEM_API.Domain.Entities;

public partial class EsExamSchedule
{
    /// <summary>
    /// รหัสการจัดตารางสอบ
    /// </summary>
    public int ScheduleId { get; set; }

    /// <summary>
    /// รหัสบุคคล
    /// </summary>
    public int EnrollmentId { get; set; }

    /// <summary>
    /// ครั้งที่สอบ เช่น ครั้งที่ 1, 2, 3 เป็นต้น
    /// </summary>
    public int PartNo { get; set; }

    /// <summary>
    /// วันที่สอบ
    /// </summary>
    public DateOnly ScheduleDate { get; set; }

    /// <summary>
    /// เวลาเริ่มสอบ
    /// </summary>
    public TimeOnly StartTime { get; set; }

    /// <summary>
    /// เวลาสิ้นสุดการสอบ
    /// </summary>
    public TimeOnly EndTime { get; set; }

    /// <summary>
    /// จำนวนข้อ
    /// </summary>
    public int TotalQuestions { get; set; }

    /// <summary>
    /// สถานะ 0 คือ ยังไม่ได้สอบ , 1 คือ สอบแล้ว, 2 คือ ไม่ได้สอบ (ยกเลิการสอบอัตโนมัติ)
    /// </summary>
    public string Status { get; set; }

    /// <summary>
    /// วันที่สร้างรายการ
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// วันที่ปรับปรุงรายการ
    /// </summary>
    public DateTime? UpdatedDate { get; set; }
}