// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EXAM_SYSTEM_API.Domain.Entities;

public partial class EsExamFinalResult
{
    /// <summary>
    /// รหัสผลสอบ
    /// </summary>
    public int ResultId { get; set; }

    /// <summary>
    /// รหัสนักเรียน
    /// </summary>
    public int PersonId { get; set; }

    /// <summary>
    /// รหัสชุดข้อสอบ
    /// </summary>
    public int ExamsetId { get; set; }

    /// <summary>
    /// คะแนนรวมจากทุก Part
    /// </summary>
    public double? TotalScore { get; set; }

    /// <summary>
    /// จำนวนวันที่สอบ
    /// </summary>
    public int TotalDays { get; set; }

    /// <summary>
    /// สถานะสอบเสร็จหรือยัง
    /// </summary>
    public string Status { get; set; }

    /// <summary>
    /// วันที่รวมคะแนนเสร็จ
    /// </summary>
    public byte[] CompletedDate { get; set; }
}