// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EXAM_SYSTEM_API.Domain.Entities;

public partial class EsExamSet
{
    /// <summary>
    /// namespace EXAM_SYSTEM_API.Domain.Entities;
    /// </summary>
    public int ExamsetId { get; set; }

    /// <summary>
    /// ประเภทชุดข้อสอบ เช่น 1 คือ GCIO, 2 คือ มาตรฐาน DG
    /// </summary>
    public int ExamsetType { get; set; }

    /// <summary>
    /// ชื่อชุดข้อสอบ
    /// </summary>
    public string ExamsetName { get; set; }

    /// <summary>
    /// รหัสมาตรฐาน
    /// </summary>
    public int StdId { get; set; }

    /// <summary>
    /// ชื่อมาตรฐาน
    /// </summary>
    public string StdName { get; set; }

    /// <summary>
    /// รายละเอียดของชุดข้อสอบ
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// จำนวนข้อสอบทั้งหมด
    /// </summary>
    public int TotalQuestions { get; set; }

    /// <summary>
    /// คะแนนเต็มของข้อสอบชุดนี้
    /// </summary>
    public int MaxScore { get; set; }

    /// <summary>
    /// เปอร์เซ็นต์ที่ต้องได้เพื่อผ่าน เช่น 60.00
    /// </summary>
    public decimal PassPercentage { get; set; }

    /// <summary>
    /// จำนวนวันที่ใช้สอบ
    /// </summary>
    public int NumDateExam { get; set; }

    /// <summary>
    /// วันที่เริ่มให้มีการสอบ
    /// </summary>
    public DateOnly StartDate { get; set; }

    /// <summary>
    /// วันที่สิ้นสุดของการสอบ
    /// </summary>
    public DateOnly EndDate { get; set; }

    /// <summary>
    /// ระยะเวลาทำข้อสอบต่อ 1 ข้อ  (หน่วย: วินาที)
    /// </summary>
    public int TimePerQuestion { get; set; }

    /// <summary>
    /// ผู้สร้างชุดข้อสอบ (เชื่อมกับ Users)
    /// </summary>
    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    /// <summary>
    /// วันที่สร้าง
    /// </summary>
    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string IsUsed { get; set; }
}