// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EXAM_SYSTEM_API.Domain.Entities;

public partial class EsExamTakenDetail
{
    public int ExamTakenDetailId { get; set; }

    /// <summary>
    /// รหัสการทำแบบทดสอบ
    /// </summary>
    public int ExamTakenId { get; set; }

    public string ChoiceAnswer { get; set; }

    /// <summary>
    /// จำนวนข้อที่ตอบถูก
    /// </summary>
    public int NumCorrect { get; set; }

    /// <summary>
    /// จำนวนข้อที่ตอบผิด
    /// </summary>
    public int NumIncorrect { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }
}