// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EXAM_SYSTEM_API.Domain.Entities;

public partial class EsExamEnrollment
{
    /// <summary>
    /// รหัสการลงทะเบียนสอบ
    /// </summary>
    public int EnrollmentId { get; set; }

    /// <summary>
    /// จำนวนที่ระบุในการสอบ
    /// </summary>
    public int NumDays { get; set; }

    /// <summary>
    /// รหัสบุคคล
    /// </summary>
    public int PersonId { get; set; }

    /// <summary>
    /// รหัสชุดข้อสอบ
    /// </summary>
    public int ExamsetId { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }
}