// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EXAM_SYSTEM_API.Domain.Entities;

public partial class EsGcioCandidate
{
    /// <summary>
    /// รหัสออโต้รัน
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// คำนำหน้าชื่อ
    /// </summary>
    public string InitialName { get; set; }

    /// <summary>
    /// ชื่อ
    /// </summary>
    public string FirstName { get; set; }

    /// <summary>
    /// นามสกุล
    /// </summary>
    public string LastName { get; set; }

    public string OrgName { get; set; }

    public string PositionName { get; set; }

    /// <summary>
    /// อีเมล
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// เบอร์โทรศัพท์
    /// </summary>
    public string MobilePhone { get; set; }

    /// <summary>
    /// หมายเหตุ
    /// </summary>
    public string Remark { get; set; }

    /// <summary>
    /// สถานะการใช้งาน 1 คือ ใช้งาน, 0 คือ ไม่ใช้งาน
    /// </summary>
    public bool IsUsed { get; set; }
}