// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EXAM_SYSTEM_API.Domain.Entities;

public partial class EsGeneratedExamQuestion
{
    /// <summary>
    /// รหัสรายการ
    /// </summary>
    public int GeneratedQuestionId { get; set; }

    /// <summary>
    /// รหัสของ Part
    /// </summary>
    public int ScheduleId { get; set; }

    /// <summary>
    /// ข้อสอบที่ถูกสุ่ม
    /// </summary>
    public int QuestionId { get; set; }
}