// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EXAM_SYSTEM_API.Domain.Entities;

public partial class EsGeneratedExamPart
{
    /// <summary>
    /// รหัสของ Part
    /// </summary>
    public int GeneratedPartId { get; set; }

    /// <summary>
    /// รหัสของรายการเลือก
    /// </summary>
    public int SelectionId { get; set; }

    /// <summary>
    /// วันที่ของการสอบ
    /// </summary>
    public int PartNumber { get; set; }

    /// <summary>
    /// จำนวนข้อสอบใน Part นี้
    /// </summary>
    public int NumQuestions { get; set; }

    /// <summary>
    /// วันที่กำหนดสอบของ Part นี้
    /// </summary>
    public DateOnly ScheduledDate { get; set; }

    /// <summary>
    /// วันที่สร้าง
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// รหัสบุคคล
    /// </summary>
    public int PersonId { get; set; }
}