// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EXAM_SYSTEM_API.Domain.Entities;

public partial class EsMultipleChoiceQuestion
{
    /// <summary>
    /// รหัสคำถาม
    /// </summary>
    public int QuestionId { get; set; }

    /// <summary>
    /// คำถาม
    /// </summary>
    public string QuestionText { get; set; }

    /// <summary>
    /// ตัวเลือก ก
    /// </summary>
    public string ChoiceA { get; set; }

    /// <summary>
    /// ตัวเลือก ข
    /// </summary>
    public string ChoiceB { get; set; }

    /// <summary>
    /// ตัวเลือก ค
    /// </summary>
    public string ChoiceC { get; set; }

    /// <summary>
    /// ตัวเลือก ง
    /// </summary>
    public string ChoiceD { get; set; }

    /// <summary>
    /// คำตอบที่ถูกต้อง
    /// </summary>
    public string CorrectAnswer { get; set; }

    /// <summary>
    /// รหัสกลุ่มมาตรฐาน
    /// </summary>
    public string StdGroup { get; set; }

    /// <summary>
    /// ออกข้อสอบตามประเภทใด ( 1คือ คุณวุฒิ, 2 คือ UOC, 3 คือ EOC,  4 คือ PC)
    /// </summary>
    public string StdType { get; set; }

    /// <summary>
    /// รหัสอ้างอิงของมาตรฐาน
    /// </summary>
    public string RefStdId { get; set; }

    /// <summary>
    /// ระดับความยากง่าย
    /// </summary>
    public string Difficulty { get; set; }

    /// <summary>
    /// วันที่สร้างรายการข้อมูล
    /// </summary>
    public DateTime CreatedDate { get; set; }

    /// <summary>
    /// ผู้สร้างรายการข้อมูล
    /// </summary>
    public string CreatedBy { get; set; }

    /// <summary>
    /// วันที่ปรับปรุงรายการข้อมูล
    /// </summary>
    public DateTime? UpdatedDate { get; set; }

    /// <summary>
    /// ผู้ปรับปรุงรายการข้อมูล
    /// </summary>
    public string UpdatedBy { get; set; }

    /// <summary>
    /// สถานะการใช้งาน 1 คือ ใช้งาน , 0 คือ ไม่ใช้งาน
    /// </summary>
    public string IsUsed { get; set; }
}