// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EXAM_SYSTEM_API.Domain.Entities;

public partial class EsQuestion
{
    /// <summary>
    /// รหัสข้อสอบ
    /// </summary>
    public int QuestionId { get; set; }

    /// <summary>
    /// เนื้อหาของคำถาม
    /// </summary>
    public string QuestionText { get; set; }

    /// <summary>
    /// ประเภทของคำถาม
    /// </summary>
    public string QuestionType { get; set; }

    /// <summary>
    /// กลุ่มมาตรฐาน
    /// </summary>
    public string StdGroup { get; set; }

    public string StdType { get; set; }

    public string RefStdId { get; set; }

    /// <summary>
    /// ระดับความยากของข้อสอบ
    /// </summary>
    public string Difficulty { get; set; }

    /// <summary>
    /// วิชาของข้อสอบ
    /// </summary>
    public string Subject { get; set; }

    /// <summary>
    /// ผู้สร้างข้อสอบ
    /// </summary>
    public string CreatedBy { get; set; }

    /// <summary>
    /// ผู้อนุมัติข้อสอบ
    /// </summary>
    public string ApprovedBy { get; set; }

    /// <summary>
    /// วันที่สร้าง
    /// </summary>
    public DateTime? CreatedDate { get; set; }

    /// <summary>
    /// วันที่อนุมัติ
    /// </summary>
    public DateTime? ApprovedAt { get; set; }
}